### ISSUE TITLE
Pod install problem

### ISSUE THREAD

**Issue by sevlaan** [RedMadRobot/core-parser#1]
Hello!
When I try to install core-parser as pod I get the next message: 

git@git.redmadrobot.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ohserezha** [comment]
The same issue here

**Comment by vani2** [comment]
Oops! Please check out updated version `2.2.3`.

**Comment by sevlaan** [comment]
Thanks a lot!
